import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/layout/Header';
import Footer from '@/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' data-theme='cupcake'>
      <body className={inter.className}>
        <Header />
        <section className='container mx-auto'>
          <main className='py-8 mx-auto md:px-4'>{children}</main>
        </section>
        <Footer />
      </body>
    </html>
  );
}
